// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),
BUILDIN_DEF(getskillname, "v"),
BUILDIN_DEF(registermacro, "rrii"),
BUILDIN_DEF(autobuff, "rri"),
BUILDIN_DEF(autopot, "rri"),
BUILDIN_DEF(autorestock, "rri"),
BUILDIN_DEF(storeindex, "ii?"),
BUILDIN_DEF(fillstorage, "ii"),